/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../../../../index";

/**
 * @example
 *     {
 *         name: "name",
 *         syncDagUpdateSyncId: "sync_id"
 *     }
 */
export interface SyncDagUpdate {
    name: string;
    description?: string;
    syncDagUpdateSyncId: string;
    nodes?: AirweaveSDK.DagNodeCreate[];
    edges?: AirweaveSDK.DagEdgeCreate[];
}
