/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AirweaveSDK from "../../../../api/index";
import * as core from "../../../../core";

export const EntityDefinitionCreateEntitySchema: core.serialization.Schema<
    serializers.EntityDefinitionCreateEntitySchema.Raw,
    AirweaveSDK.EntityDefinitionCreateEntitySchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.string()),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace EntityDefinitionCreateEntitySchema {
    export type Raw = string[] | Record<string, unknown>;
}
