/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as AirweaveSDK from "../../../../../api/index";
import * as core from "../../../../../core";

export const UserCreate: core.serialization.Schema<
    serializers.UserCreate.Raw,
    Omit<AirweaveSDK.UserCreate, "creds">
> = core.serialization.object({
    email: core.serialization.string(),
    fullName: core.serialization.property("full_name", core.serialization.string().optional()),
    organizationId: core.serialization.property("organization_id", core.serialization.string().optional()),
});

export declare namespace UserCreate {
    export interface Raw {
        email: string;
        full_name?: string | null;
        organization_id?: string | null;
    }
}
