/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         fromEntityId: "from_entity_id",
 *         toEntityId: "to_entity_id"
 *     }
 */
export interface EntityRelationCreate {
    name: string;
    description?: string;
    fromEntityId: string;
    toEntityId: string;
}
