/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id",
 *         creds: "creds"
 *     }
 */
export interface DeleteApiKeyApiKeysDeleteRequest {
    id: string;
    creds: string;
}
