/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AirweaveSDK from "../../../../api/index";
import * as core from "../../../../core";
import { SearchResult } from "../../../types/SearchResult";

export const Response: core.serialization.Schema<serializers.search.search.Response.Raw, AirweaveSDK.SearchResult[]> =
    core.serialization.list(SearchResult);

export declare namespace Response {
    export type Raw = SearchResult.Raw[];
}
