/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         creds: "creds",
 *         body: "string"
 *     }
 */
export interface SendOauth2WhiteLabelCodeConnectionsOauth2WhiteLabelWhiteLabelIdCodePostRequest {
    creds: string;
    body: string;
}
