export { BodyConnectIntegrationConnectionsConnectIntegrationTypeShortNamePost } from "./BodyConnectIntegrationConnectionsConnectIntegrationTypeShortNamePost";
export { BodySendOauth2CodeConnectionsOauth2SourceCodePost } from "./BodySendOauth2CodeConnectionsOauth2SourceCodePost";
export { BodyConnectSlackWithTokenConnectionsDirectTokenSlackPost } from "./BodyConnectSlackWithTokenConnectionsDirectTokenSlackPost";
