/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as AirweaveSDK from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Collections {
    export interface Options {
        environment?: core.Supplier<environments.AirweaveSDKEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the X-Framework-Name header */
        frameworkName?: core.Supplier<string | undefined>;
        /** Override the X-Framework-Version header */
        frameworkVersion?: core.Supplier<string | undefined>;
        /** Override the X-Organization-ID header */
        organizationId?: core.Supplier<(string | null) | undefined>;
        /** Override the x-agent-key header */
        agentKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Framework-Name header */
        frameworkName?: string | undefined;
        /** Override the X-Framework-Version header */
        frameworkVersion?: string | undefined;
        /** Override the X-Organization-ID header */
        organizationId?: (string | null) | undefined;
        /** Override the x-agent-key header */
        agentKey?: string;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * API endpoints for managing collections - logical groups of data sources that provide unified search capabilities
 */
export class Collections {
    protected readonly _options: Collections.Options;

    constructor(_options: Collections.Options) {
        this._options = _options;
    }

    /**
     * List all collections that belong to your organization with optional search filtering.
     *
     * Collections are always sorted by creation date (newest first).
     *
     * @param {AirweaveSDK.ListCollectionsGetRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.list()
     */
    public list(
        request: AirweaveSDK.ListCollectionsGetRequest = {},
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.Collection[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: AirweaveSDK.ListCollectionsGetRequest = {},
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.Collection[]>> {
        const { skip, limit, search } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        if (search != null) {
            _queryParams["search"] = search;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                "collections",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.Collection[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError("Timeout exceeded when calling GET /collections.");
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new collection.
     *
     * Only organization owners and admins can create collections.
     * The creator is automatically assigned as collection_owner.
     *
     * The newly created collection is initially empty and does not contain any data
     * until you explicitly add source connections to it.
     *
     * @param {AirweaveSDK.CollectionCreate} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.create({
     *         name: "Finance Data",
     *         description: "Financial reports and analytics data",
     *         color: "#10b981",
     *         icon: "chart-bar",
     *         readable_id: "finance-data-reports"
     *     })
     */
    public create(
        request: AirweaveSDK.CollectionCreate,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.Collection> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: AirweaveSDK.CollectionCreate,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.Collection>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                "collections",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.Collection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError("Timeout exceeded when calling POST /collections.");
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a specific collection by its readable ID.
     *
     * @param {AirweaveSDK.GetCollectionsReadableIdGetRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.get({
     *         readable_id: "readable_id"
     *     })
     */
    public get(
        request: AirweaveSDK.GetCollectionsReadableIdGetRequest,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.Collection> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: AirweaveSDK.GetCollectionsReadableIdGetRequest,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.Collection>> {
        const { readable_id: readableId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                `collections/${encodeURIComponent(readableId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.Collection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError(
                    "Timeout exceeded when calling GET /collections/{readable_id}.",
                );
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a collection and all associated data.
     *
     * Only organization owners/admins and collection owners can delete collections.
     *
     * Permanently removes a collection from your organization including all synced data
     * from the destination systems. All source connections within this collection
     * will also be deleted as part of the cleanup process. This action cannot be undone.
     *
     * @param {AirweaveSDK.DeleteCollectionsReadableIdDeleteRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.delete({
     *         readable_id: "readable_id"
     *     })
     */
    public delete(
        request: AirweaveSDK.DeleteCollectionsReadableIdDeleteRequest,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.Collection> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: AirweaveSDK.DeleteCollectionsReadableIdDeleteRequest,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.Collection>> {
        const { readable_id: readableId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                `collections/${encodeURIComponent(readableId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.Collection, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError(
                    "Timeout exceeded when calling DELETE /collections/{readable_id}.",
                );
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Trigger data synchronization for all source connections in the collection.
     *
     * Only organization owners/admins, collection owners and collection editors can refresh collections.
     *
     * The sync jobs run asynchronously in the background, so this endpoint
     * returns immediately with job details that you can use to track progress. You can
     * monitor the status of individual data synchronization using the source connection
     * endpoints.
     *
     * @param {AirweaveSDK.RefreshAllSourceConnectionsCollectionsReadableIdRefreshAllPostRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.refreshAllSourceConnections({
     *         readable_id: "readable_id"
     *     })
     */
    public refreshAllSourceConnections(
        request: AirweaveSDK.RefreshAllSourceConnectionsCollectionsReadableIdRefreshAllPostRequest,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.SourceConnectionJob[]> {
        return core.HttpResponsePromise.fromPromise(this.__refreshAllSourceConnections(request, requestOptions));
    }

    private async __refreshAllSourceConnections(
        request: AirweaveSDK.RefreshAllSourceConnectionsCollectionsReadableIdRefreshAllPostRequest,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.SourceConnectionJob[]>> {
        const { readable_id: readableId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                `collections/${encodeURIComponent(readableId)}/refresh_all`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.SourceConnectionJob[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError(
                    "Timeout exceeded when calling POST /collections/{readable_id}/refresh_all.",
                );
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Legacy GET search endpoint for backwards compatibility.
     *
     * DEPRECATED: This endpoint uses the old schema. Please migrate to POST with the new
     * SearchRequest format for access to all features.
     *
     * @param {AirweaveSDK.SearchGetLegacyCollectionsReadableIdSearchGetRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.searchGetLegacy({
     *         readable_id: "readable_id",
     *         query: "query"
     *     })
     */
    public searchGetLegacy(
        request: AirweaveSDK.SearchGetLegacyCollectionsReadableIdSearchGetRequest,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.LegacySearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchGetLegacy(request, requestOptions));
    }

    private async __searchGetLegacy(
        request: AirweaveSDK.SearchGetLegacyCollectionsReadableIdSearchGetRequest,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.LegacySearchResponse>> {
        const {
            readable_id: readableId,
            query,
            response_type: responseType,
            limit,
            offset,
            recency_bias: recencyBias,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["query"] = query;
        if (responseType != null) {
            _queryParams["response_type"] = responseType;
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        if (offset != null) {
            _queryParams["offset"] = offset.toString();
        }

        if (recencyBias !== undefined) {
            _queryParams["recency_bias"] = recencyBias?.toString() ?? null;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                `collections/${encodeURIComponent(readableId)}/search`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as AirweaveSDK.LegacySearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError(
                    "Timeout exceeded when calling GET /collections/{readable_id}/search.",
                );
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Search your collection.
     *
     * Accepts both new SearchRequest and legacy LegacySearchRequest formats
     * for backwards compatibility.
     *
     * @param {AirweaveSDK.SearchCollectionsReadableIdSearchPostRequest} request
     * @param {Collections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AirweaveSDK.UnprocessableEntityError}
     *
     * @example
     *     await client.collections.search({
     *         readable_id: "readable_id",
     *         body: {
     *             query: "query"
     *         }
     *     })
     */
    public search(
        request: AirweaveSDK.SearchCollectionsReadableIdSearchPostRequest,
        requestOptions?: Collections.RequestOptions,
    ): core.HttpResponsePromise<AirweaveSDK.SearchCollectionsReadableIdSearchPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__search(request, requestOptions));
    }

    private async __search(
        request: AirweaveSDK.SearchCollectionsReadableIdSearchPostRequest,
        requestOptions?: Collections.RequestOptions,
    ): Promise<core.WithRawResponse<AirweaveSDK.SearchCollectionsReadableIdSearchPostResponse>> {
        const { readable_id: readableId, body: _body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Framework-Name": requestOptions?.frameworkName ?? this._options?.frameworkName,
                "X-Framework-Version": requestOptions?.frameworkVersion ?? this._options?.frameworkVersion,
                "X-Organization-ID": requestOptions?.organizationId ?? this._options?.organizationId,
                "x-agent-key": requestOptions?.agentKey ?? this._options?.agentKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AirweaveSDKEnvironment.Production,
                `collections/${encodeURIComponent(readableId)}/search`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as AirweaveSDK.SearchCollectionsReadableIdSearchPostResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AirweaveSDK.UnprocessableEntityError(
                        _response.error.body as AirweaveSDK.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AirweaveSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AirweaveSDKError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AirweaveSDKTimeoutError(
                    "Timeout exceeded when calling POST /collections/{readable_id}/search.",
                );
            case "unknown":
                throw new errors.AirweaveSDKError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
