/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         creds: "creds",
 *         name: undefined,
 *         redirectUrl: undefined,
 *         clientId: undefined,
 *         clientSecret: undefined
 *     }
 */
export interface WhiteLabelUpdate {
    creds: string;
    name?: string;
    redirectUrl?: string;
    clientId?: string;
    clientSecret?: string;
}
