/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request body for checking multiple actions at once.
 */
export interface ActionCheckRequest {
    /** Map of action short name to amount to check */
    actions: Record<string, number>;
}
