/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Destination options for admin search.
 */
export type AdminSearchDestination = "qdrant" | "vespa";
export const AdminSearchDestination = {
    Qdrant: "qdrant",
    Vespa: "vespa",
} as const;
