/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Request schema for agentic search.
 */
export interface AgenticSearchRequest {
    /** The natural language search query. */
    query: string;
    /** Filter groups that are always applied to search results. Conditions within a group are combined with AND. Multiple groups are combined with OR. Leave empty for no filtering. */
    filter?: AirweaveSDK.AgenticSearchFilterGroup[];
    /** The search mode. 'fast' performs a single search pass. 'thinking' performs an intelligent multi-step search to find the best results (may take longer). Defaults to 'thinking'. */
    mode?: AirweaveSDK.AgenticSearchMode;
    /** Maximum number of results to return. The response will contain at most this many results, but the agent can decide to return fewer. When not set, all results are returned. */
    limit?: number;
}
