/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for updating an existing agent API key.
 *
 * All fields are optional for partial updates.
 */
export interface AgentApiKeyUpdate {
    name?: string | null;
    description?: string | null;
    status?: AirweaveSDK.AgentApiKeyStatus | null;
    is_read_only?: boolean | null;
    rate_limit_per_minute?: number | null;
    rate_limit_per_hour?: number | null;
    rate_limit_per_day?: number | null;
    expires_at?: string | null;
    auto_renew?: boolean | null;
}
