/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

export type AgenticSearchEvent =
    | AirweaveSDK.AgenticSearchEvent.Started
    | AirweaveSDK.AgenticSearchEvent.Thinking
    | AirweaveSDK.AgenticSearchEvent.ToolCall
    | AirweaveSDK.AgenticSearchEvent.Reranking
    | AirweaveSDK.AgenticSearchEvent.Done
    | AirweaveSDK.AgenticSearchEvent.Error_;

export namespace AgenticSearchEvent {
    export interface Started extends AirweaveSDK.AgenticSearchStartedEvent {
        type: "started";
    }

    export interface Thinking extends AirweaveSDK.AgenticSearchThinkingEvent {
        type: "thinking";
    }

    export interface ToolCall extends AirweaveSDK.AgenticSearchToolCallEvent {
        type: "tool_call";
    }

    export interface Reranking extends AirweaveSDK.AgenticSearchRerankingEvent {
        type: "reranking";
    }

    export interface Done extends AirweaveSDK.AgenticSearchDoneEvent {
        type: "done";
    }

    export interface Error_ extends AirweaveSDK.AgenticSearchErrorEvent {
        type: "error";
    }
}
