/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * A single filter condition.
 *
 * Pydantic validates that:
 * - ``field`` is a valid AgenticSearchFilterableField enum value
 * - ``operator`` is a valid AgenticSearchFilterOperator enum value
 * - ``value`` matches the expected types
 * - The combination of field + operator + value is semantically valid
 *
 * Invalid filters raise ``pydantic.ValidationError`` automatically.
 *
 * Examples:
 *     {"field": "airweave_system_metadata.source_name", "operator": "equals",
 *      "value": "notion"}
 *     {"field": "created_at", "operator": "greater_than",
 *      "value": "2024-01-01T00:00:00Z"}
 *     {"field": "breadcrumbs.name", "operator": "contains", "value": "Engineering"}
 */
export interface AgenticSearchFilterCondition {
    /** Field to filter on (use dot notation for nested fields). */
    field: AirweaveSDK.AgenticSearchFilterableField;
    /** The comparison operator to use. */
    operator: AirweaveSDK.AgenticSearchFilterOperator;
    /** Value to compare against. Use a list for 'in' and 'not_in' operators. */
    value: AgenticSearchFilterCondition.Value;
}

export namespace AgenticSearchFilterCondition {
    /**
     * Value to compare against. Use a list for 'in' and 'not_in' operators.
     */
    export type Value = string | number | number | boolean | string[] | number[];
}
