/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Types of audit actions for catalog governance.
 */
export type AuditActionType =
    | "CREATE"
    | "UPDATE"
    | "DELETE"
    | "INCLUDE_IN_RAG"
    | "EXCLUDE_FROM_RAG"
    | "STATUS_CHANGE"
    | "DEPRECATE"
    | "ARCHIVE"
    | "REACTIVATE"
    | "CONTENT_UPDATE"
    | "RESYNC"
    | "RECHUNK"
    | "MOVE"
    | "REPARENT"
    | "REVIEW"
    | "APPROVE"
    | "REJECT"
    | "BULK_INCLUDE"
    | "BULK_EXCLUDE"
    | "BULK_STATUS_CHANGE"
    | "BULK_UPDATE_SENSITIVITY";
export const AuditActionType = {
    Create: "CREATE",
    Update: "UPDATE",
    Delete: "DELETE",
    IncludeInRag: "INCLUDE_IN_RAG",
    ExcludeFromRag: "EXCLUDE_FROM_RAG",
    StatusChange: "STATUS_CHANGE",
    Deprecate: "DEPRECATE",
    Archive: "ARCHIVE",
    Reactivate: "REACTIVATE",
    ContentUpdate: "CONTENT_UPDATE",
    Resync: "RESYNC",
    Rechunk: "RECHUNK",
    Move: "MOVE",
    Reparent: "REPARENT",
    Review: "REVIEW",
    Approve: "APPROVE",
    Reject: "REJECT",
    BulkInclude: "BULK_INCLUDE",
    BulkExclude: "BULK_EXCLUDE",
    BulkStatusChange: "BULK_STATUS_CHANGE",
    BulkUpdateSensitivity: "BULK_UPDATE_SENSITIVITY",
} as const;
