/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Authentication methods for source connections.
 */
export type AuthenticationMethod = "direct" | "oauth_browser" | "oauth_token" | "oauth_byoc" | "auth_provider";
export const AuthenticationMethod = {
    Direct: "direct",
    OauthBrowser: "oauth_browser",
    OauthToken: "oauth_token",
    OauthByoc: "oauth_byoc",
    AuthProvider: "auth_provider",
} as const;
