/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for creating an auth provider connection with credentials.
 */
export interface AuthProviderConnectionCreate {
    /** Human-readable name for this auth provider connection */
    name: string;
    /** URL-safe unique identifier for the connection. Must contain only lowercase letters, numbers, and hyphens. If not provided, it will be automatically generated from the connection name with a random suffix for uniqueness (e.g., 'composio-connection-ab123'). */
    readable_id?: string;
    /** Optional detailed description of what this auth provider connection provides. */
    description?: string;
    /** Technical identifier of the auth provider */
    short_name: string;
    /** Authentication credentials required to access the auth provider. The required fields vary by auth provider type. */
    auth_fields?: AirweaveSDK.ConfigValues;
}
