/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BackgroundTaskStatus = "running" | "finished" | "failed";
export const BackgroundTaskStatus = {
    Running: "running",
    Finished: "finished",
    Failed: "failed",
} as const;
