/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BackgroundTaskType =
    | "endpoint.replay"
    | "endpoint.recover"
    | "application.stats"
    | "message.broadcast"
    | "sdk.generate"
    | "event-type.aggregate"
    | "application.purge_content"
    | "endpoint.bulk_replay";
export const BackgroundTaskType = {
    EndpointReplay: "endpoint.replay",
    EndpointRecover: "endpoint.recover",
    ApplicationStats: "application.stats",
    MessageBroadcast: "message.broadcast",
    SdkGenerate: "sdk.generate",
    EventTypeAggregate: "event-type.aggregate",
    ApplicationPurgeContent: "application.purge_content",
    EndpointBulkReplay: "endpoint.bulk_replay",
} as const;
