/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Billing plan tiers.
 */
export type BillingPlan = "trial" | "developer" | "pro" | "team" | "enterprise";
export const BillingPlan = {
    Trial: "trial",
    Developer: "developer",
    Pro: "pro",
    Team: "team",
    Enterprise: "enterprise",
} as const;
