/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

export interface BodyResyncWithExecutionConfigAdminResyncSyncIdPost {
    /** Optional nested SyncConfig for sync behavior (destinations, handlers, cursor, behavior) */
    execution_config?: AirweaveSDK.SyncConfig;
    /** Optional tags for filtering and organizing sync jobs (e.g., ['vespa-backfill-01-22-2026', 'manual']) */
    tags?: string[];
}
