/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BodyCreateCredentialsFromAuthorizationCodeSourceConnectionsSourceShortNameCodeToTokenCredentialsPost {
    /** Custom name for the stored credential */
    credential_name?: string;
    /** Description to help identify this credential */
    credential_description?: string;
    /** OAuth client ID (required for bring-your-own-credentials) */
    client_id?: string;
    /** OAuth client secret (required for bring-your-own-credentials) */
    client_secret?: string;
}
