/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Catalog item with governance-specific metadata.
 */
export interface CatalogItemWithGovernance {
    entity_id: string;
    title: string;
    description?: string | null;
    tags?: string[] | null;
    asset_type: string;
    source_external_id?: string | null;
    source_url?: string | null;
    source_name?: string | null;
    parent_catalog_id?: string | null;
    hierarchy_path?: string | null;
    depth_level?: number;
    include_in_rag?: boolean;
    status?: AirweaveSDK.CatalogStatus;
    sensitivity_level?: AirweaveSDK.SensitivityLevel;
    id: string;
    sync_id: string;
    collection_id: string;
    entity_db_id?: string | null;
    entity_definition_id?: string | null;
    source_id?: string | null;
    content_hash?: string | null;
    last_content_update?: string | null;
    last_embedded?: string | null;
    chunk_count?: number;
    created_at?: string | null;
    modified_at?: string | null;
    created_by?: string | null;
    updated_by?: string | null;
    rag_eligibility: Record<string, unknown>;
    governance_health: Record<string, unknown>;
    last_audit_entry?: Record<string, unknown> | null;
}
