/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Complete tree view for a collection's catalog.
 */
export interface CatalogTreeView {
    collection_id: string;
    root_nodes: AirweaveSDK.CatalogTreeNode[];
    total_items: number;
    selected_items: number;
    total_chunks: number;
}
