/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for creating a chat.
 */
export interface ChatCreate {
    name: string;
    syncId: string;
    description?: string;
    modelName?: string;
    modelSettings?: Record<string, unknown>;
    searchSettings?: Record<string, unknown>;
}
