/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for creating a chat message.
 */
export interface ChatMessageCreate {
    content: string;
    role?: string;
}
