/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for updating a chat.
 */
export interface ChatUpdate {
    name?: string;
    description?: string;
    modelSettings?: Record<string, unknown>;
    searchSettings?: Record<string, unknown>;
}
