/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Chat response that extends search response with conversation info.
 */
export interface ChatResponse {
    /** Array of search result objects containing the found documents, records, or data entities. */
    results: Record<string, unknown>[];
    /** This provides natural language answers to your query based on the content found across your connected data sources when generate_answer is true. */
    completion: string | null;
    /** ID of the conversation */
    conversation_id: string;
    /** ID of the assistant's response message */
    message_id: string;
    /** Whether the conversation was closed due to limits */
    conversation_closed?: boolean;
}
