/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Classic search request — LLM generates a search plan, execute against Vespa.
 */
export interface ClassicSearchRequest {
    /** Search query text. */
    query: string;
    /** Filter groups (combined with OR). */
    filter?: AirweaveSDK.FilterGroup[];
    /** Max results to return. */
    limit?: number;
    /** Number of results to skip. */
    offset?: number;
}
