/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Role of a user within a collection.
 */
export type CollectionRole = "collection_owner" | "collection_editor" | "collection_viewer";
export const CollectionRole = {
    CollectionOwner: "collection_owner",
    CollectionEditor: "collection_editor",
    CollectionViewer: "collection_viewer",
} as const;
