/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Config field model.
 */
export interface ConfigField {
    name: string;
    title: string;
    description?: string;
    type: string;
}
