/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Context cluster with associated catalog items.
 */
export interface ContextClusterWithItems {
    name: string;
    description?: string | null;
    tags?: string[] | null;
    include_in_rag?: boolean;
    status?: AirweaveSDK.ContextClusterStatus;
    id: string;
    collection_id: string;
    usage_count?: number;
    last_used_at?: string | null;
    created_at?: string | null;
    modified_at?: string | null;
    created_by_email?: string | null;
    modified_by_email?: string | null;
    catalog_items?: AirweaveSDK.CatalogItemSummary[];
    item_count?: number;
}
