/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Statistics about content updates.
 */
export interface ContentUpdateStats {
    total_updates: number;
    updates_by_source: Record<string, number>;
    updates_by_day: Record<string, number>;
    average_updates_per_day: number;
    most_active_source?: string | null;
}
