/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Request model for creating a new webhook subscription.
 */
export interface CreateSubscriptionRequest {
    url: string;
    event_types: AirweaveSDK.EventType[];
    secret?: string;
}
