/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for a DAG edge.
 */
export interface DagEdge {
    from_node_id: string;
    to_node_id: string;
    id: string;
    dag_id: string;
    organization_id: string;
    created_by_email?: string;
    modified_by_email?: string;
}
