/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for Destination with auth config.
 */
export interface DestinationWithAuthenticationFields {
    name: string;
    description?: string;
    short_name: string;
    class_name: string;
    auth_config_class?: string;
    input_entity_definition_ids?: string[];
    organization_id?: string;
    config_schema?: Record<string, unknown>;
    labels?: string[];
    id: string;
    created_at: string;
    modified_at: string;
    auth_fields?: AirweaveSDK.Fields;
}
