/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for updating an entity relation.
 */
export interface EntityRelationUpdate {
    name: string;
    description?: string;
    fromEntityId: string;
    toEntityId: string;
}
