/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Entity count with entity definition details.
 *
 * After the entity_definition table elimination, name/type/description
 * are populated from the in-memory registry or derived from the short_name.
 */
export interface EntityCountWithDefinition {
    count: number;
    entity_definition_short_name: string;
    entity_definition_name: string;
    entity_definition_type: string;
    entity_definition_description?: string;
    modified_at: string;
}
