/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EventType =
    | "sync.pending"
    | "sync.running"
    | "sync.completed"
    | "sync.failed"
    | "sync.cancelled"
    | "entity.batch_processed"
    | "query.processed"
    | "access_control.batch_processed"
    | "collection.created"
    | "collection.updated"
    | "collection.deleted"
    | "source_connection.created"
    | "source_connection.auth_completed"
    | "source_connection.deleted";
export const EventType = {
    SyncPending: "sync.pending",
    SyncRunning: "sync.running",
    SyncCompleted: "sync.completed",
    SyncFailed: "sync.failed",
    SyncCancelled: "sync.cancelled",
    EntityBatchProcessed: "entity.batch_processed",
    QueryProcessed: "query.processed",
    AccessControlBatchProcessed: "access_control.batch_processed",
    CollectionCreated: "collection.created",
    CollectionUpdated: "collection.updated",
    CollectionDeleted: "collection.deleted",
    SourceConnectionCreated: "source_connection.created",
    SourceConnectionAuthCompleted: "source_connection.auth_completed",
    SourceConnectionDeleted: "source_connection.deleted",
} as const;
