/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Geo filter request  Matches coordinates inside the rectangle, described by coordinates of lop-left and bottom-right edges
 */
export interface GeoBoundingBox {
    /** Geo filter request  Matches coordinates inside the rectangle, described by coordinates of lop-left and bottom-right edges */
    top_left: AirweaveSDK.GeoPoint;
    /** Geo filter request  Matches coordinates inside the rectangle, described by coordinates of lop-left and bottom-right edges */
    bottom_right: AirweaveSDK.GeoPoint;
}
