/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

/**
 * Integration credential in DB without decrypted data.
 */
export interface IntegrationCredentialInDb {
    name: string;
    integrationShortName: string;
    description?: string;
    integrationType: AirweaveSDK.IntegrationType;
    authType: AirweaveSDK.AuthType;
    authConfigClass?: string;
    id: string;
    organizationId: string;
    encryptedCredentials: string;
}
