/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Admin-only agentic search request with model override for evals.
 */
export interface InternalAgenticSearchRequest {
    /** Search query text. */
    query: string;
    /** Enable extended thinking / chain-of-thought. */
    thinking?: boolean;
    /** Filter groups (combined with OR). */
    filter?: AirweaveSDK.FilterGroup[];
    /** Max results. None means agent decides. */
    limit?: number;
    /** LLM model override. Format: 'provider/model' e.g. 'together/zai-glm-5-thinking'. When not set, uses the default model from config. */
    model?: string;
}
