/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Legacy search response schema for backwards compatibility.
 */
export interface LegacySearchResponse {
    /** Array of search result objects */
    results: Record<string, unknown>[];
    /** Indicates whether results are raw search matches or AI-generated completions */
    response_type: AirweaveSDK.ResponseType;
    /** AI-generated natural language answer when response_type is 'completion' */
    completion?: string;
    /** Status of the search operation */
    status: AirweaveSDK.SearchStatus;
}
