/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Full-text match of at least one token of the string.
 */
export interface MatchTextAny {
    /** Full-text match of at least one token of the string. */
    text_any: string;
}
