/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MessageStatusText = "success" | "pending" | "fail" | "sending";
export const MessageStatusText = {
    Success: "success",
    Pending: "pending",
    Fail: "fail",
    Sending: "sending",
} as const;
