/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OAuth authentication via browser flow.
 */
export interface OAuthBrowserAuth {
    /** OAuth redirect URI */
    redirect_uri?: string;
}
