/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * OAuth token types for sources.
 */
export type OAuthType = "access_only" | "with_refresh" | "with_rotating_refresh";
export const OAuthType = {
    AccessOnly: "access_only",
    WithRefresh: "with_refresh",
    WithRotatingRefresh: "with_rotating_refresh",
} as const;
