/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Organization schema with user's role information.
 */
export interface OrganizationWithRole {
    id: string;
    name: string;
    description?: string;
    created_at: string;
    modified_at: string;
    role: string;
    is_primary: boolean;
    auth0_org_id?: string;
    org_metadata?: Record<string, unknown>;
}
