/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response indicating if organization is ready for use after creation.
 */
export interface OrganizationReadinessResponse {
    /** Whether organization is ready for use */
    ready: boolean;
    /** Optional message about readiness status */
    message?: string | null;
}
