/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Request to validate organization creation with a specific plan.
 */
export interface OrganizationCreationValidationRequest {
    /** Billing plan to validate */
    billing_plan: AirweaveSDK.BillingPlan;
}
