/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Organization schema with user's role information.
 */
export interface OrganizationWithRole {
    id: string;
    name: string;
    description?: string;
    created_at: string;
    modified_at: string;
    role: string;
    is_primary: boolean;
    auth0_org_id?: string;
    org_metadata?: Record<string, unknown>;
    /** List of enabled feature flags for this organization */
    enabled_features?: AirweaveSDK.FeatureFlag[];
    /** Complete billing information including current period */
    billing?: AirweaveSDK.OrganizationBilling;
}
