/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Request model for updating an existing webhook subscription.
 */
export interface PatchSubscriptionRequest {
    url?: string;
    event_types?: AirweaveSDK.EventType[];
}
