/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response format options for search results.
 */
export type ResponseType = "raw" | "completion";
export const ResponseType = {
    Raw: "raw",
    Completion: "completion",
} as const;
