/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request to configure S3 destination.
 */
export interface S3ConfigRequest {
    /** AWS access key ID */
    aws_access_key_id: string;
    /** AWS secret access key */
    aws_secret_access_key: string;
    /** S3 bucket name */
    bucket_name: string;
    /** Prefix for Graffo data */
    bucket_prefix?: string;
    /** AWS region */
    aws_region?: string;
    /** Custom S3 endpoint */
    endpoint_url?: string | null;
    /** Use SSL/TLS */
    use_ssl?: boolean;
}
