/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Comprehensive search response containing results and metadata.
 */
export interface SearchResponse {
    /** Array of search result objects containing the found documents, records, or data entities. */
    results: Record<string, unknown>[];
    /** This provides natural language answers to your query based on the content found across your connected data sources when generate_answer is true. */
    completion?: string;
}
