/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

/**
 * Schema for search response.
 */
export interface SearchResponse {
    results: Record<string, unknown>[];
    responseType: AirweaveSDK.ResponseType;
    completion?: string;
    status: AirweaveSDK.SearchStatus;
}
