/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Unified response for all search tiers.
 */
export interface SearchV2Response {
    /** Search results ordered by relevance. */
    results?: AirweaveSDK.SearchResult[];
}
