/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Minimal source connection for list views with computed fields.
 */
export interface SourceConnectionListItem {
    id: string;
    name: string;
    short_name: string;
    readable_collection_id: string;
    created_at: string;
    modified_at: string;
    is_authenticated: boolean;
    readable_auth_provider_id?: string;
    connection_init_session_id?: string;
    is_active?: boolean;
    last_sync?: AirweaveSDK.SyncSummary;
    entity_count?: number;
    last_job_status?: AirweaveSDK.SyncJobStatus;
    /** Compute authentication method from database fields. */
    auth_method: AirweaveSDK.AuthenticationMethod;
    /** Compute connection status from current state. */
    status: AirweaveSDK.SourceConnectionStatus;
}
