/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Minimal source connection for list views.
 */
export interface SourceConnectionListItem {
    id: string;
    name: string;
    short_name: string;
    readable_collection_id: string;
    status: AirweaveSDK.SourceConnectionStatus;
    auth_method: AirweaveSDK.AuthenticationMethod;
    created_at: string;
    modified_at: string;
    last_sync?: AirweaveSDK.SyncSummary;
    entity_count?: number;
}
