/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request schema for updating rate limits via API.
 */
export interface SourceRateLimitUpdateRequest {
    /** Maximum requests allowed per window */
    limit: number;
    /** Time window in seconds */
    window_seconds: number;
}
