/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Complete source rate limit schema.
 */
export interface SourceRateLimit {
    /** Source identifier (e.g., 'google_drive', 'notion') */
    source_short_name: string;
    /** Maximum requests allowed per window */
    limit: number;
    /** Time window in seconds (60=per minute, 86400=per day, etc.) */
    window_seconds?: number;
    id: string;
    organization_id: string;
    created_at: string;
    modified_at: string;
}
