/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Source connection status enum - represents overall connection state.
 */
export type SourceConnectionStatus = "active" | "pending_auth" | "syncing" | "error" | "inactive" | "pending_sync";
export const SourceConnectionStatus = {
    Active: "active",
    PendingAuth: "pending_auth",
    Syncing: "syncing",
    Error: "error",
    Inactive: "inactive",
    PendingSync: "pending_sync",
} as const;
