/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

/**
 * Schema for SourceConnectionJob.
 *
 * This is a public schema that is used to return sync jobs for a source connection.
 * Sync / sync jobs are system tables, and are not exposed to the public API.
 */
export interface SourceConnectionJob {
    sourceConnectionId: string;
    id: string;
    organizationId: string;
    createdByEmail: string;
    modifiedByEmail: string;
    createdAt: Date;
    modifiedAt: Date;
    status?: AirweaveSDK.SyncJobStatus;
    entitiesInserted?: number;
    entitiesUpdated?: number;
    entitiesDeleted?: number;
    entitiesKept?: number;
    entitiesSkipped?: number;
    entitiesEncountered?: Record<string, number | undefined>;
    startedAt?: Date;
    completedAt?: Date;
    failedAt?: Date;
    error?: string;
}
