/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for SyncJob.
 */
export interface SyncJob {
    sync_id: string;
    status?: AirweaveSDK.SyncJobStatus;
    scheduled?: boolean;
    entities_inserted?: number | null;
    entities_updated?: number | null;
    entities_deleted?: number | null;
    entities_kept?: number | null;
    entities_skipped?: number | null;
    entities_encountered?: Record<string, number | null> | null;
    started_at?: string | null;
    completed_at?: string | null;
    failed_at?: string | null;
    error?: string | null;
    access_token?: string | null;
    id: string;
    organization_id: string;
    created_by_email?: string | null;
    modified_by_email?: string | null;
    created_at?: string | null;
    modified_at?: string | null;
    /** Name of the sync, populated from join query */
    sync_name?: string | null;
}
