/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

/**
 * Schema for a sync DAG definition.
 *
 * The DAG structure as the UI displays it.
 *
 * This means that for each entity, there is a node that is the producer and a node that is the
 * consumer. These are connected by an edge: producer -edge-> entity -edge-> consumer
 *
 * Sources, transformers, and destinations are also nodes, but they do not have an
 * entity_definition_id.
 *
 * Sources are producers by default, and destinations are consumers by default.
 * Transformers are both producers and consumers.
 */
export interface SyncDag {
    name: string;
    description?: string;
    syncId: string;
    id: string;
    organizationId: string;
    createdByEmail: string;
    modifiedByEmail: string;
    nodes: AirweaveSDK.DagNode[];
    edges: AirweaveSDK.DagEdge[];
}
