/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

/**
 * Schema for Sync.
 */
export interface Sync {
    name: string;
    sourceConnectionId: string;
    embeddingModelConnectionId?: string;
    destinationConnectionIds: string[];
    description?: string;
    cronSchedule?: string;
    nextScheduledRun?: Date;
    syncMetadata?: Record<string, unknown>;
    status: AirweaveSDK.SyncStatus;
    id: string;
    organizationId: string;
    createdAt: Date;
    modifiedAt: Date;
    createdByEmail: string;
    modifiedByEmail: string;
}
