/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for updating a Sync object.
 */
export interface SyncUpdate {
    name?: string | null;
    cron_schedule?: string | null;
    next_scheduled_run?: string | null;
    sync_metadata?: Record<string, unknown> | null;
    status?: AirweaveSDK.SyncStatus | null;
    temporal_schedule_id?: string | null;
    sync_type?: string | null;
}
