/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Schema for creating a Sync object.
 */
export interface SyncCreate {
    name: string;
    source_connection_id: string;
    destination_connection_ids: string[];
    description?: string;
    cron_schedule?: string;
    next_scheduled_run?: string;
    temporal_schedule_id?: string;
    sync_type?: string;
    sync_metadata?: Record<string, unknown>;
    sync_config?: AirweaveSDK.SyncConfig;
    status?: AirweaveSDK.SyncStatus;
    run_immediately?: boolean;
}
