/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for creating a transformer.
 */
export interface TransformerCreate {
    name: string;
    description?: string;
    method_name: string;
    module_name: string;
    input_entity_definition_ids: string[];
    output_entity_definition_ids: string[];
    config_schema?: Record<string, unknown>;
}
