/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Summary of user activity for governance reporting.
 */
export interface UserActivitySummary {
    user_email: string;
    user_name: string;
    total_actions: number;
    action_breakdown: Record<string, number>;
    most_recent_action?: string | null;
    collections_affected?: string[];
}
