/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Schema for User.
 */
export interface User {
    email: string;
    fullName?: string;
    organizationId?: string;
    id: string;
    permissions?: string[];
}
