/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index";

export interface ValidationError {
    loc: AirweaveSDK.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
