/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request body for verifying OAuth flow ownership.
 */
export interface VerifyOAuthRequest {
    /** Claim token from create response */
    claim_token: string;
}
