/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * Full subscription detail, including delivery attempts and signing secret.
 *
 * Returned by ``GET /subscriptions/{id}`` only.
 */
export interface WebhookSubscriptionDetail {
    /** Unique identifier for this subscription (UUID format) */
    id: string;
    /** The URL where webhook events are delivered */
    url: string;
    /** Event types this subscription is filtered to receive. See EventType enum for all available types. */
    filter_types?: string[];
    /** Whether this subscription is currently disabled. Disabled subscriptions do not receive event deliveries. */
    disabled?: boolean;
    /** Optional human-readable description of this subscription */
    description?: string;
    /** When this subscription was created (ISO 8601 format, UTC) */
    created_at: string;
    /** When this subscription was last updated (ISO 8601 format, UTC) */
    updated_at: string;
    /** Health status of this subscription based on recent delivery attempts. Values: 'healthy' (all recent deliveries succeeded), 'degraded' (mix of successes and failures), 'failing' (consecutive failures beyond threshold), 'unknown' (no delivery data yet). */
    health_status?: AirweaveSDK.HealthStatus;
    /** Recent delivery attempts for this subscription. */
    delivery_attempts?: AirweaveSDK.DeliveryAttempt[];
    /** The signing secret for webhook signature verification. Only included when include_secret=true is passed to the API. Keep this secret secure. */
    secret?: string;
}
