/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../index.js";

/**
 * A webhook subscription (endpoint) configuration.
 */
export interface WebhookSubscription {
    /** Unique identifier for this subscription (UUID format) */
    id: string;
    /** The URL where webhook events are delivered */
    url: string;
    /** Event types this subscription is filtered to receive. See EventType enum for all available types. */
    filter_types?: string[];
    /** Whether this subscription is currently disabled. Disabled subscriptions do not receive event deliveries. */
    disabled?: boolean;
    /** Optional human-readable description of this subscription */
    description?: string;
    /** When this subscription was created (ISO 8601 format, UTC) */
    created_at: string;
    /** When this subscription was last updated (ISO 8601 format, UTC) */
    updated_at: string;
    /** Recent delivery attempts for this subscription. Only included when fetching a single subscription via GET /subscriptions/{id}. */
    delivery_attempts?: AirweaveSDK.DeliveryAttempt[];
    /** The signing secret for webhook signature verification. Only included when include_secret=true is passed to the API. Keep this secret secure. */
    secret?: string;
}
