/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         skip: 0,
 *         limit: 100,
 *         search: "customer"
 *     }
 */
export interface ListCollectionsGetRequest {
    /** Number of collections to skip for pagination */
    skip?: number;
    /** Maximum number of collections to return (1-1000) */
    limit?: number;
    /** Search term to filter collections by name or readable_id */
    search?: string;
}
