/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../../../../index";

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface SearchCollectionCollectionsReadableIdSearchGetRequest {
    /**
     * Search query
     */
    query: string;
    /**
     * Type of response: raw search results or AI completion
     */
    responseType?: AirweaveSDK.ResponseType;
}
