/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         source_connection_id: "source_connection_id"
 *     }
 */
export interface DeleteSourceConnectionsSourceConnectionIdDeleteRequest {
    source_connection_id: string;
}
