/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetSourceConnectionSourceConnectionsSourceConnectionIdGetRequest {
    /**
     * Whether to reveal authentication credentials.
     */
    show_auth_fields?: boolean;
}
