/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AirweaveSDK from "../../../../api/index";
import * as core from "../../../../core";
import { Collection } from "../../../types/Collection";

export const Response: core.serialization.Schema<
    serializers.collections.listCollections.Response.Raw,
    AirweaveSDK.Collection[]
> = core.serialization.list(Collection);

export declare namespace Response {
    export type Raw = Collection.Raw[];
}
