/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../../../../index";

/**
 * @example
 *     {
 *         query: "query",
 *         body: undefined
 *     }
 */
export interface SearchSearchObjectsPostRequest {
    query: string;
    syncId?: string;
    body?: AirweaveSDK.MetadataSearchFilter[];
}
