/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AirweaveSDK from "../../api/index";
import * as core from "../../core";
import { ChatMessage } from "./ChatMessage";

export const Chat: core.serialization.ObjectSchema<serializers.Chat.Raw, AirweaveSDK.Chat> = core.serialization.object({
    name: core.serialization.string(),
    syncId: core.serialization.property("sync_id", core.serialization.string()),
    description: core.serialization.string().optional(),
    modelName: core.serialization.property("model_name", core.serialization.string().optional()),
    modelSettings: core.serialization.property(
        "model_settings",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    searchSettings: core.serialization.property(
        "search_settings",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    id: core.serialization.string(),
    messages: core.serialization.list(ChatMessage).optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    modifiedAt: core.serialization.property("modified_at", core.serialization.date()),
    createdByEmail: core.serialization.property("created_by_email", core.serialization.string()),
    modifiedByEmail: core.serialization.property("modified_by_email", core.serialization.string()),
    organizationId: core.serialization.property("organization_id", core.serialization.string()),
});

export declare namespace Chat {
    export interface Raw {
        name: string;
        sync_id: string;
        description?: string | null;
        model_name?: string | null;
        model_settings?: Record<string, unknown> | null;
        search_settings?: Record<string, unknown> | null;
        id: string;
        messages?: ChatMessage.Raw[] | null;
        created_at: string;
        modified_at: string;
        created_by_email: string;
        modified_by_email: string;
        organization_id: string;
    }
}
