/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AirweaveSDK from "../../api/index";
import * as core from "../../core";

export const CollectionStatus: core.serialization.Schema<
    serializers.CollectionStatus.Raw,
    AirweaveSDK.CollectionStatus
> = core.serialization.enum_(["ACTIVE", "PARTIAL ERROR", "NEEDS SOURCE", "ERROR"]);

export declare namespace CollectionStatus {
    export type Raw = "ACTIVE" | "PARTIAL ERROR" | "NEEDS SOURCE" | "ERROR";
}
