/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AirweaveSDK from "../../api/index";
import * as core from "../../core";

export const DagEdge: core.serialization.ObjectSchema<serializers.DagEdge.Raw, AirweaveSDK.DagEdge> =
    core.serialization.object({
        fromNodeId: core.serialization.property("from_node_id", core.serialization.string()),
        toNodeId: core.serialization.property("to_node_id", core.serialization.string()),
        id: core.serialization.string(),
        dagId: core.serialization.property("dag_id", core.serialization.string()),
        organizationId: core.serialization.property("organization_id", core.serialization.string()),
        createdByEmail: core.serialization.property("created_by_email", core.serialization.string()),
        modifiedByEmail: core.serialization.property("modified_by_email", core.serialization.string()),
    });

export declare namespace DagEdge {
    export interface Raw {
        from_node_id: string;
        to_node_id: string;
        id: string;
        dag_id: string;
        organization_id: string;
        created_by_email: string;
        modified_by_email: string;
    }
}
