/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AirweaveSDK from "../../api/index";
import * as core from "../../core";

export const OAuth2AuthUrl: core.serialization.ObjectSchema<serializers.OAuth2AuthUrl.Raw, AirweaveSDK.OAuth2AuthUrl> =
    core.serialization.object({
        url: core.serialization.string(),
    });

export declare namespace OAuth2AuthUrl {
    export interface Raw {
        url: string;
    }
}
