/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         creds: "creds"
 *     }
 */
export interface DeleteSyncSyncSyncIdDeleteRequest {
    deleteData?: boolean;
    creds: string;
}
