/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListSyncsSyncGetRequest {
    skip?: number;
    limit?: number;
    withSourceConnection?: boolean;
}
