/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         sourceConnectionId: "source_connection_id"
 *     }
 */
export interface SyncCreate {
    name: string;
    description?: string;
    sourceConnectionId: string;
    destinationConnectionId?: string;
    embeddingModelConnectionId?: string;
    cronSchedule?: string;
    whiteLabelId?: string;
    whiteLabelUserIdentifier?: string;
    syncMetadata?: Record<string, unknown>;
    runImmediately?: boolean;
}
