/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as AirweaveSDK from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SyncUpdate {
    name?: string;
    cronSchedule?: string;
    nextScheduledRun?: Date;
    whiteLabelId?: string;
    whiteLabelUserIdentifier?: string;
    syncMetadata?: Record<string, unknown>;
    status?: AirweaveSDK.SyncStatus;
}
