/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AirweaveSDK from "../../../../api/index";
import * as core from "../../../../core";
import { Sync } from "../../../types/Sync";
import { SyncWithSourceConnection } from "../../../types/SyncWithSourceConnection";

export const ListSyncsSyncGetResponse: core.serialization.Schema<
    serializers.ListSyncsSyncGetResponse.Raw,
    AirweaveSDK.ListSyncsSyncGetResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(Sync),
    core.serialization.list(SyncWithSourceConnection),
]);

export declare namespace ListSyncsSyncGetResponse {
    export type Raw = Sync.Raw[] | SyncWithSourceConnection.Raw[];
}
