/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { AirweaveSDKClient } from "../../src/Client";
import * as AirweaveSDK from "../../src/api/index";

describe("Collections", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                name: "Finance Data",
                readable_id: "finance-data-ab123",
                id: "550e8400-e29b-41d4-a716-446655440000",
                created_at: "2024-01-15T09:30:00Z",
                modified_at: "2024-01-15T14:22:15Z",
                organization_id: "org12345-6789-abcd-ef01-234567890abc",
                created_by_email: "admin@company.com",
                modified_by_email: "finance@company.com",
                status: "ACTIVE",
                vector_size: 1,
                embedding_model_name: "embedding_model_name",
                source_connection_summaries: [{ short_name: "short_name", name: "name" }],
            },
        ];
        server.mockEndpoint().get("/collections").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.collections.list({
            skip: 0,
            limit: 100,
            search: "customer",
        });
        expect(response).toEqual([
            {
                name: "Finance Data",
                readable_id: "finance-data-ab123",
                id: "550e8400-e29b-41d4-a716-446655440000",
                created_at: "2024-01-15T09:30:00Z",
                modified_at: "2024-01-15T14:22:15Z",
                organization_id: "org12345-6789-abcd-ef01-234567890abc",
                created_by_email: "admin@company.com",
                modified_by_email: "finance@company.com",
                status: "ACTIVE",
                vector_size: 1,
                embedding_model_name: "embedding_model_name",
                source_connection_summaries: [
                    {
                        short_name: "short_name",
                        name: "name",
                    },
                ],
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/collections").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.collections.list();
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail" };
        server.mockEndpoint().get("/collections").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.collections.list();
        }).rejects.toThrow(AirweaveSDK.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Finance Data", readable_id: "finance-data-reports" };
        const rawResponseBody = {
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: { skip_load: true, skip_updates: true },
                behavior: { skip_hash_comparison: true, replay_from_arf: true, skip_guardrails: true },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                { short_name: "slack", name: "Slack" },
                { short_name: "github", name: "GitHub" },
            ],
        };
        server
            .mockEndpoint()
            .post("/collections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.create({
            name: "Finance Data",
            readable_id: "finance-data-reports",
        });
        expect(response).toEqual({
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: {
                    skip_load: true,
                    skip_updates: true,
                },
                behavior: {
                    skip_hash_comparison: true,
                    replay_from_arf: true,
                    skip_guardrails: true,
                },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                {
                    short_name: "slack",
                    name: "Slack",
                },
                {
                    short_name: "github",
                    name: "GitHub",
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "buzz", readable_id: undefined, sync_config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/collections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.create({
                name: "buzz",
                readable_id: undefined,
                sync_config: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "buzz", readable_id: undefined, sync_config: undefined };
        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .post("/collections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.create({
                name: "buzz",
                readable_id: undefined,
                sync_config: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: { skip_load: true, skip_updates: true },
                behavior: { skip_hash_comparison: true, replay_from_arf: true, skip_guardrails: true },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                { short_name: "slack", name: "Slack" },
                { short_name: "github", name: "GitHub" },
            ],
        };
        server
            .mockEndpoint()
            .get("/collections/customer-support-tickets-x7k9m")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.get("customer-support-tickets-x7k9m");
        expect(response).toEqual({
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: {
                    skip_load: true,
                    skip_updates: true,
                },
                behavior: {
                    skip_hash_comparison: true,
                    replay_from_arf: true,
                    skip_guardrails: true,
                },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                {
                    short_name: "slack",
                    name: "Slack",
                },
                {
                    short_name: "github",
                    name: "GitHub",
                },
            ],
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .get("/collections/readable_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.get("readable_id");
        }).rejects.toThrow(AirweaveSDK.NotFoundError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/collections/readable_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.get("readable_id");
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .get("/collections/readable_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.get("readable_id");
        }).rejects.toThrow(AirweaveSDK.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: { skip_load: true, skip_updates: true },
                behavior: { skip_hash_comparison: true, replay_from_arf: true, skip_guardrails: true },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                { short_name: "slack", name: "Slack" },
                { short_name: "github", name: "GitHub" },
            ],
        };
        server
            .mockEndpoint()
            .delete("/collections/customer-support-tickets-x7k9m")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.delete("customer-support-tickets-x7k9m");
        expect(response).toEqual({
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: {
                    skip_load: true,
                    skip_updates: true,
                },
                behavior: {
                    skip_hash_comparison: true,
                    replay_from_arf: true,
                    skip_guardrails: true,
                },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                {
                    short_name: "slack",
                    name: "Slack",
                },
                {
                    short_name: "github",
                    name: "GitHub",
                },
            ],
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .delete("/collections/readable_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.delete("readable_id");
        }).rejects.toThrow(AirweaveSDK.NotFoundError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/collections/readable_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.delete("readable_id");
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .delete("/collections/readable_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.delete("readable_id");
        }).rejects.toThrow(AirweaveSDK.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Updated Finance Data" };
        const rawResponseBody = {
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: { skip_load: true, skip_updates: true },
                behavior: { skip_hash_comparison: true, replay_from_arf: true, skip_guardrails: true },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                { short_name: "slack", name: "Slack" },
                { short_name: "github", name: "GitHub" },
            ],
        };
        server
            .mockEndpoint()
            .patch("/collections/customer-support-tickets-x7k9m")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.update("customer-support-tickets-x7k9m", {
            name: "Updated Finance Data",
        });
        expect(response).toEqual({
            name: "Finance Data",
            readable_id: "finance-data-ab123",
            id: "550e8400-e29b-41d4-a716-446655440000",
            sync_config: {
                destinations: {
                    skip_vespa: true,
                    target_destinations: ["target_destinations"],
                    exclude_destinations: ["exclude_destinations"],
                },
                handlers: {
                    enable_vector_handlers: true,
                    enable_raw_data_handler: true,
                    enable_postgres_handler: true,
                },
                cursor: {
                    skip_load: true,
                    skip_updates: true,
                },
                behavior: {
                    skip_hash_comparison: true,
                    replay_from_arf: true,
                    skip_guardrails: true,
                },
            },
            created_at: "2024-01-15T09:30:00Z",
            modified_at: "2024-01-15T14:22:15Z",
            organization_id: "org12345-6789-abcd-ef01-234567890abc",
            created_by_email: "admin@company.com",
            modified_by_email: "finance@company.com",
            status: "ACTIVE",
            vector_size: 3072,
            embedding_model_name: "text-embedding-3-large",
            source_connection_summaries: [
                {
                    short_name: "slack",
                    name: "Slack",
                },
                {
                    short_name: "github",
                    name: "GitHub",
                },
            ],
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, sync_config: undefined };
        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .patch("/collections/readable_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.update("readable_id", {
                name: undefined,
                sync_config: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.NotFoundError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, sync_config: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/collections/readable_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.update("readable_id", {
                name: undefined,
                sync_config: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: undefined, sync_config: undefined };
        const rawResponseBody = { detail: "detail" };
        server
            .mockEndpoint()
            .patch("/collections/readable_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.update("readable_id", {
                name: undefined,
                sync_config: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.TooManyRequestsError);
    });

    test("instantSearch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        { entity_id: "ws-1", name: "Acme Workspace", entity_type: "NotionWorkspaceEntity" },
                        { entity_id: "db-eng", name: "Engineering", entity_type: "NotionDatabaseEntity" },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: { archived: false, icon: "🚀", parent_type: "database_id" },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        { entity_id: "team-1", name: "Acme", entity_type: "SlackWorkspaceEntity" },
                        { entity_id: "chan-eng", name: "#engineering", entity_type: "SlackChannelEntity" },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: { channel_name: "#engineering", username: "alice" },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/instant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.instantSearch("readable_id", {
            query: "query",
        });
        expect(response).toEqual({
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        {
                            entity_id: "ws-1",
                            name: "Acme Workspace",
                            entity_type: "NotionWorkspaceEntity",
                        },
                        {
                            entity_id: "db-eng",
                            name: "Engineering",
                            entity_type: "NotionDatabaseEntity",
                        },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: {
                        archived: false,
                        icon: "\uD83D\uDE80",
                        parent_type: "database_id",
                    },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        {
                            entity_id: "team-1",
                            name: "Acme",
                            entity_type: "SlackWorkspaceEntity",
                        },
                        {
                            entity_id: "chan-eng",
                            name: "#engineering",
                            entity_type: "SlackChannelEntity",
                        },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: {
                        channel_name: "#engineering",
                        username: "alice",
                    },
                },
            ],
        });
    });

    test("instantSearch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            query: "query",
            retrieval_strategy: undefined,
            filter: undefined,
            limit: undefined,
            offset: undefined,
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/instant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.instantSearch("readable_id", {
                query: "query",
                retrieval_strategy: undefined,
                filter: undefined,
                limit: undefined,
                offset: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("classicSearch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        { entity_id: "ws-1", name: "Acme Workspace", entity_type: "NotionWorkspaceEntity" },
                        { entity_id: "db-eng", name: "Engineering", entity_type: "NotionDatabaseEntity" },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: { archived: false, icon: "🚀", parent_type: "database_id" },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        { entity_id: "team-1", name: "Acme", entity_type: "SlackWorkspaceEntity" },
                        { entity_id: "chan-eng", name: "#engineering", entity_type: "SlackChannelEntity" },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: { channel_name: "#engineering", username: "alice" },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/classic")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.classicSearch("readable_id", {
            query: "query",
        });
        expect(response).toEqual({
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        {
                            entity_id: "ws-1",
                            name: "Acme Workspace",
                            entity_type: "NotionWorkspaceEntity",
                        },
                        {
                            entity_id: "db-eng",
                            name: "Engineering",
                            entity_type: "NotionDatabaseEntity",
                        },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: {
                        archived: false,
                        icon: "\uD83D\uDE80",
                        parent_type: "database_id",
                    },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        {
                            entity_id: "team-1",
                            name: "Acme",
                            entity_type: "SlackWorkspaceEntity",
                        },
                        {
                            entity_id: "chan-eng",
                            name: "#engineering",
                            entity_type: "SlackChannelEntity",
                        },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: {
                        channel_name: "#engineering",
                        username: "alice",
                    },
                },
            ],
        });
    });

    test("classicSearch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query", filter: undefined, limit: undefined, offset: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/classic")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.classicSearch("readable_id", {
                query: "query",
                filter: undefined,
                limit: undefined,
                offset: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });

    test("agenticSearch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        { entity_id: "ws-1", name: "Acme Workspace", entity_type: "NotionWorkspaceEntity" },
                        { entity_id: "db-eng", name: "Engineering", entity_type: "NotionDatabaseEntity" },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: { archived: false, icon: "🚀", parent_type: "database_id" },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        { entity_id: "team-1", name: "Acme", entity_type: "SlackWorkspaceEntity" },
                        { entity_id: "chan-eng", name: "#engineering", entity_type: "SlackChannelEntity" },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: { channel_name: "#engineering", username: "alice" },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/agentic")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.collections.agenticSearch("readable_id", {
            query: "query",
        });
        expect(response).toEqual({
            results: [
                {
                    entity_id: "page-abc123",
                    name: "Production Deployment Guide",
                    relevance_score: 0.94,
                    breadcrumbs: [
                        {
                            entity_id: "ws-1",
                            name: "Acme Workspace",
                            entity_type: "NotionWorkspaceEntity",
                        },
                        {
                            entity_id: "db-eng",
                            name: "Engineering",
                            entity_type: "NotionDatabaseEntity",
                        },
                    ],
                    created_at: "2025-02-10T09:15:00Z",
                    updated_at: "2025-03-18T16:30:00Z",
                    textual_representation:
                        "# Production Deployment Guide\n\nThis document covers the standard deployment process for production releases.",
                    airweave_system_metadata: {
                        source_name: "notion",
                        entity_type: "NotionPageEntity",
                        sync_id: "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80",
                        sync_job_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                        chunk_index: 0,
                        original_entity_id: "page-abc123",
                    },
                    access: {},
                    web_url: "https://notion.so/Deployment-Guide-abc123",
                    url: "url",
                    raw_source_fields: {
                        archived: false,
                        icon: "\uD83D\uDE80",
                        parent_type: "database_id",
                    },
                },
                {
                    entity_id: "msg-def456",
                    name: "Deployment checklist update",
                    relevance_score: 0.87,
                    breadcrumbs: [
                        {
                            entity_id: "team-1",
                            name: "Acme",
                            entity_type: "SlackWorkspaceEntity",
                        },
                        {
                            entity_id: "chan-eng",
                            name: "#engineering",
                            entity_type: "SlackChannelEntity",
                        },
                    ],
                    created_at: "2025-03-15T11:22:00Z",
                    updated_at: "2025-03-15T11:22:00Z",
                    textual_representation:
                        "Updated the deployment checklist to include the new canary step. Make sure to verify metrics before promoting to 100%.",
                    airweave_system_metadata: {
                        source_name: "slack",
                        entity_type: "SlackMessageEntity",
                        sync_id: "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091",
                        sync_job_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                        chunk_index: 0,
                        original_entity_id: "msg-def456",
                    },
                    access: {},
                    web_url: "https://acme.slack.com/archives/C0123ABC/p1710500520",
                    url: "url",
                    raw_source_fields: {
                        channel_name: "#engineering",
                        username: "alice",
                    },
                },
            ],
        });
    });

    test("agenticSearch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new AirweaveSDKClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query", thinking: undefined, filter: undefined, limit: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/collections/readable_id/search/agentic")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.collections.agenticSearch("readable_id", {
                query: "query",
                thinking: undefined,
                filter: undefined,
                limit: undefined,
            });
        }).rejects.toThrow(AirweaveSDK.UnprocessableEntityError);
    });
});
