/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Sources } from "./api/resources/sources/client/Client.js";
import { AuthProviders } from "./api/resources/authProviders/client/Client.js";
import { Collections } from "./api/resources/collections/client/Client.js";
import { SourceConnections } from "./api/resources/sourceConnections/client/Client.js";
import { WhiteLabels } from "./api/resources/whiteLabels/client/Client.js";

export declare namespace AirweaveSDKClient {
    export interface Options {
        environment?: core.Supplier<environments.AirweaveSDKEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class AirweaveSDKClient {
    protected readonly _options: AirweaveSDKClient.Options;
    protected _sources: Sources | undefined;
    protected _authProviders: AuthProviders | undefined;
    protected _collections: Collections | undefined;
    protected _sourceConnections: SourceConnections | undefined;
    protected _whiteLabels: WhiteLabels | undefined;

    constructor(_options: AirweaveSDKClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@airweave/sdk",
                    "X-Fern-SDK-Version": "v0.5.4",
                    "User-Agent": "@airweave/sdk/v0.5.4",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get sources(): Sources {
        return (this._sources ??= new Sources(this._options));
    }

    public get authProviders(): AuthProviders {
        return (this._authProviders ??= new AuthProviders(this._options));
    }

    public get collections(): Collections {
        return (this._collections ??= new Collections(this._options));
    }

    public get sourceConnections(): SourceConnections {
        return (this._sourceConnections ??= new SourceConnections(this._options));
    }

    public get whiteLabels(): WhiteLabels {
        return (this._whiteLabels ??= new WhiteLabels(this._options));
    }
}
