/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AirweaveSDK from "../../../../api/index";
import * as core from "../../../../core";
import { Connection } from "../../../types/Connection";

export const Response: core.serialization.Schema<
    serializers.connections.listAllConnectedIntegrations.Response.Raw,
    AirweaveSDK.Connection[]
> = core.serialization.list(Connection);

export declare namespace Response {
    export type Raw = Connection.Raw[];
}
